# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - LASTD222

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'SubscriptionId'
        required: true
      resourceGroupName:
        description: 'Resource group name'
        required: true

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "subscription id: ${{github.event.inputs.subscriptionId}}"
          echo "resource group name: ${{ github.event.inputs.resourceGroupName }}" 
      - uses: azure/arm-deploy@v1
        with:
            subscriptionId: ${{github.event.inputs.subscriptionId}}
            #resourceGroupName: 'DefaultResourceGroup-EUS'
            template: ./ARMTemplates/template.json
            parameters: ./ARMTemplates/parameters.json