# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - LASTD222

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # inputs:
      # subscriptionId:
      #   description: 'SubscriptionId'
      #   required: true
      # resourceGroupName:
      #   description: 'Resource group name'
      #   required: true

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azcliversion: 'latest'
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2DB57B8EEB054D6292F9462AC8C45A4C }}
      - uses: actions/checkout@v4
      - run: |
          echo "subscription id: ${{github.event.inputs.subscriptionId}}"
          echo "resource group name: ${{ github.event.inputs.resourceGroupName }}" 
      - uses: azure/arm-deploy@v1
        with:
            subscriptionId: 'dfcee046-6355-47a1-8b62-057fc99c1fda'
            resourceGroupName: 'DefaultResourceGroup-EUS'
            template: ./ARMTemplates/template.json
            parameters: ./ARMTemplates/parameters.json