# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - lastd222

on:
  push:
    branches:
      - stg
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Create project folder
        run: |
          mkdir output
          cp 'host.json' 'output/'
          cp -r 'wf1' 'output/'
          cp 'connections.json' 'output/'
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          dest: '${{ github.run_id }}.zip'
          files: output/

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'lastdstg222'
          slot-name: 'Production'
          package: '${{ github.run_id }}.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_23A0C8FE233846F19C73CA2F5E650775 }}